/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VatRouteImport } from './routes/vat'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PayrollRouteImport } from './routes/payroll'
import { Route as ManagementReportingRouteImport } from './routes/management-reporting'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as CpaSupportRouteImport } from './routes/cpa-support'
import { Route as CorporateTaxRouteImport } from './routes/corporate-tax'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BusinessSetupRouteImport } from './routes/business-setup'
import { Route as BookCleanupRouteImport } from './routes/book-cleanup'
import { Route as AccountingRouteImport } from './routes/accounting'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const VatRoute = VatRouteImport.update({
  id: '/vat',
  path: '/vat',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollRoute = PayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementReportingRoute = ManagementReportingRouteImport.update({
  id: '/management-reporting',
  path: '/management-reporting',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const CpaSupportRoute = CpaSupportRouteImport.update({
  id: '/cpa-support',
  path: '/cpa-support',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateTaxRoute = CorporateTaxRouteImport.update({
  id: '/corporate-tax',
  path: '/corporate-tax',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessSetupRoute = BusinessSetupRouteImport.update({
  id: '/business-setup',
  path: '/business-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const BookCleanupRoute = BookCleanupRouteImport.update({
  id: '/book-cleanup',
  path: '/book-cleanup',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingRoute = AccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accounting': typeof AccountingRoute
  '/book-cleanup': typeof BookCleanupRoute
  '/business-setup': typeof BusinessSetupRoute
  '/contact': typeof ContactRoute
  '/corporate-tax': typeof CorporateTaxRoute
  '/cpa-support': typeof CpaSupportRoute
  '/industries': typeof IndustriesRoute
  '/management-reporting': typeof ManagementReportingRoute
  '/payroll': typeof PayrollRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vat': typeof VatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accounting': typeof AccountingRoute
  '/book-cleanup': typeof BookCleanupRoute
  '/business-setup': typeof BusinessSetupRoute
  '/contact': typeof ContactRoute
  '/corporate-tax': typeof CorporateTaxRoute
  '/cpa-support': typeof CpaSupportRoute
  '/industries': typeof IndustriesRoute
  '/management-reporting': typeof ManagementReportingRoute
  '/payroll': typeof PayrollRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vat': typeof VatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accounting': typeof AccountingRoute
  '/book-cleanup': typeof BookCleanupRoute
  '/business-setup': typeof BusinessSetupRoute
  '/contact': typeof ContactRoute
  '/corporate-tax': typeof CorporateTaxRoute
  '/cpa-support': typeof CpaSupportRoute
  '/industries': typeof IndustriesRoute
  '/management-reporting': typeof ManagementReportingRoute
  '/payroll': typeof PayrollRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vat': typeof VatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accounting'
    | '/book-cleanup'
    | '/business-setup'
    | '/contact'
    | '/corporate-tax'
    | '/cpa-support'
    | '/industries'
    | '/management-reporting'
    | '/payroll'
    | '/resources'
    | '/services'
    | '/sitemap.xml'
    | '/vat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accounting'
    | '/book-cleanup'
    | '/business-setup'
    | '/contact'
    | '/corporate-tax'
    | '/cpa-support'
    | '/industries'
    | '/management-reporting'
    | '/payroll'
    | '/resources'
    | '/services'
    | '/sitemap.xml'
    | '/vat'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accounting'
    | '/book-cleanup'
    | '/business-setup'
    | '/contact'
    | '/corporate-tax'
    | '/cpa-support'
    | '/industries'
    | '/management-reporting'
    | '/payroll'
    | '/resources'
    | '/services'
    | '/sitemap.xml'
    | '/vat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountingRoute: typeof AccountingRoute
  BookCleanupRoute: typeof BookCleanupRoute
  BusinessSetupRoute: typeof BusinessSetupRoute
  ContactRoute: typeof ContactRoute
  CorporateTaxRoute: typeof CorporateTaxRoute
  CpaSupportRoute: typeof CpaSupportRoute
  IndustriesRoute: typeof IndustriesRoute
  ManagementReportingRoute: typeof ManagementReportingRoute
  PayrollRoute: typeof PayrollRoute
  ResourcesRoute: typeof ResourcesRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VatRoute: typeof VatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vat': {
      id: '/vat'
      path: '/vat'
      fullPath: '/vat'
      preLoaderRoute: typeof VatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll': {
      id: '/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof PayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management-reporting': {
      id: '/management-reporting'
      path: '/management-reporting'
      fullPath: '/management-reporting'
      preLoaderRoute: typeof ManagementReportingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cpa-support': {
      id: '/cpa-support'
      path: '/cpa-support'
      fullPath: '/cpa-support'
      preLoaderRoute: typeof CpaSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate-tax': {
      id: '/corporate-tax'
      path: '/corporate-tax'
      fullPath: '/corporate-tax'
      preLoaderRoute: typeof CorporateTaxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-setup': {
      id: '/business-setup'
      path: '/business-setup'
      fullPath: '/business-setup'
      preLoaderRoute: typeof BusinessSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-cleanup': {
      id: '/book-cleanup'
      path: '/book-cleanup'
      fullPath: '/book-cleanup'
      preLoaderRoute: typeof BookCleanupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting': {
      id: '/accounting'
      path: '/accounting'
      fullPath: '/accounting'
      preLoaderRoute: typeof AccountingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountingRoute: AccountingRoute,
  BookCleanupRoute: BookCleanupRoute,
  BusinessSetupRoute: BusinessSetupRoute,
  ContactRoute: ContactRoute,
  CorporateTaxRoute: CorporateTaxRoute,
  CpaSupportRoute: CpaSupportRoute,
  IndustriesRoute: IndustriesRoute,
  ManagementReportingRoute: ManagementReportingRoute,
  PayrollRoute: PayrollRoute,
  ResourcesRoute: ResourcesRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VatRoute: VatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
